services:
  wrapdf:
    # simple mode - wrapdf/wrapdf-simple:latest
    # default mode - wrapdf/wrapdf:latest
    image: wrapdf/wrapdf-simple:latest
    container_name: wrapdf
    restart: unless-stopped
    ports:
      - '8080:8080'
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
